export const ADD_LIST = "ADD_LIST";
export const ARCHIVE_LIST = "ARCHIVE_LIST";
export const RESTORE_LIST = "RESTORE_LIST";

export const ADD_CARD = "ADD_CARD";
export const MOVE_CARD = "MOVE_CARD";
export const COPY_CARD = "COPY_CARD";
export const ARCHIVE_CARD = "ARCHIVE_CARD";
export const RESTORE_CARD = "RESTORE_CARD";
export const UPDATE_CARD_DESCRIPTION = "UPDATE_CARD_DESCRIPTION";

export const ADD_CHECKLIST_ITEM = "ADD_CHECKLIST_ITEM";
export const CHECK_CHECKLIST_ITEM = "CHECK_CHECKLIST_ITEM";
export const DELETE_CHECKLIST_ITEM = "DELETE_CHECKLIST_ITEM";
