export const FETCH_USER = "FETCH_USER";

export const FETCH_BOARD_DATA = "FETCH_BOARD_DATA";

export const UNLOAD_BOARD = "UNLOAD_BOARD";
export const UPDATE_BOARD = "UPDATE_BOARD";

export const ADD_LIST = "ADD_LIST";
export const ARCHIVE_LIST = "ARCHIVE_LIST";
export const RESTORE_LIST = "RESTORE_LIST";

export const ADD_CARD = "ADD_CARD";
export const MOVE_CARD = "MOVE_CARD";
export const COPY_CARD = "COPY_CARD";
export const ARCHIVE_CARD = "ARCHIVE_CARD";
export const RESTORE_CARD = "RESTORE_CARD";
export const UPDATE_CARD_DESCRIPTION = "UPDATE_CARD_DESCRIPTION";

export const UPDATE_CHECKLIST = "UPDATE_CHECKLIST";
export const DELETE_CHECKLIST_ITEM = "DELETE_CHECKLIST_ITEM";
