export default {
  ADD_CARD: "ADD_CARD",
  MOVE_CARD: "MOVE_CARD",
  ARCHIVE_CARD: "ARCHIVE_CARD",
  RESTORE_CARD: "RESTORE_CARD",
  UPDATE_CARD_DESCRIPTION: "UPDATE_CARD_DESCRIPTION",
  UPDATE_CHECKLIST: "UPDATE_CHECKLIST"
};
