export const ADD_LIST = "ADD_LIST";
export const ARCHIVE_LIST = "ARCHIVE_LIST";
export const RESTORE_LIST = "RESTORE_LIST";
export const ADD_CARD = "ADD_CARD";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAILURE = "ADD_CARD_FAILURE";
export const MOVE_CARD = "MOVE_CARD";
export const MOVE_CARD_SUCCESS = "MOVE_CARD_SUCCESS";
export const MOVE_CARD_FAILURE = "MOVE_CARD_FAILURE";
export const ARCHIVE_CARD = "ARCHIVE_CARD";
export const ARCHIVE_CARD_SUCCESS = "ARCHIVE_CARD_SUCCESS";
export const ARCHIVE_CARD_FAILURE = "ARCHIVE_CARD_FAILURE";
export const RESTORE_CARD = "RESTORE_CARD";
export const RESTORE_CARD_SUCCESS = "RESTORE_CARD_SUCCESS";
export const RESTORE_CARD_FAILURE = "RESTORE_CARD_FAILURE";
export const UPDATE_CARD_DESCRIPTION = "UPDATE_CARD_DESCRIPTION";
export const UPDATE_CARD_DESCRIPTION_SUCCESS =
  "UPDATE_CARD_DESCRIPTION_SUCCESS";
export const UPDATE_CARD_DESCRIPTION_FAILURE =
  "UPDATE_CARD_DESCRIPTION_FAILURE";
export const UPDATE_CHECKLIST = "UPDATE_CHECKLIST";
export const FETCH_BOARD_DATA = "FETCH_BOARD_DATA";
export const PENDING_BOARD_BACKGROUND = "PENDING_BOARD_BACKGROUND";
export const UNLOAD_BOARD = "UNLOAD_BOARD";
export const UPDATE_BOARD = "UPDATE_BOARD";
export const FETCH_USER = "FETCH_USER";
