export default {
  ADD_LIST: "ADD_LIST",
  ARCHIVE_LIST: "ARCHIVE_LIST",
  RESTORE_LIST: "RESTORE_LIST",
  ADD_CARD: "ADD_CARD",
  ADD_CARD_SUCCESS: "ADD_CARD_SUCCESS",
  ADD_CARD_FAILURE: "ADD_CARD_FAILURE",
  MOVE_CARD: "MOVE_CARD",
  ARCHIVE_CARD: "ARCHIVE_CARD",
  RESTORE_CARD: "RESTORE_CARD",
  UPDATE_CARD_DESCRIPTION: "UPDATE_CARD_DESCRIPTION",
  UPDATE_CHECKLIST: "UPDATE_CHECKLIST",
  FETCH_BOARD_DATA: "FETCH_BOARD_DATA",
  PENDING_BOARD_BACKGROUND: "PENDING_BOARD_BACKGROUND",
  UNLOAD_BOARD: "UNLOAD_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  FETCH_USER: "FETCH_USER"
};
